import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from "next/dynamic";
const HeroSection = dynamic(()=>import('../components/HeroSection'))

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSection/>
      </main>
    </div>

  )
}
